### ISSUE TITLE
[Question] Entity Name Replaced by Identifier String

### ISSUE THREAD

**Issue by joaopedros2** [t0bst4r/home-assistant-matter-hub#116]
I'm encountering an issue with the entity name when it contains special characters or exceeds a certain length. Specifically, my Home Assistant entity originally named "Luz da Cama - Quarto do Guilherme" is exposed in Matter as "Luz da Cama - Quarto do 0e5caab0".

Could you confirm if this behavior is intended or if there is a bug that causes part of the name to be replaced by an identifier? Additionally, if there are specific naming guidelines or restrictions for entities in Matter, that information would be very helpful.

Thank you for your assistance!

**Comment by t0bst4r** [comment]
Yes, this is intended.
The `nodeLabel` cannot be longer than 32 characters.

So if the name is shorter than or equal to 32 chars, it is used.
If it is longer than 32, only the first 24 chars are used and a 8 char hash is added instead. Having that, users are always able to identify it with the User Interface. At least in Alexa you can rename your devices (locally for Alexa only). I thought this is possible for the others, too, so I thought its fine.

While thinking about it, I'll change it to 28 chars and a 4 char hash, but anyway the root cause remains.
