### ISSUE TITLE
Problem with reverse proxy: Unexpected token 'T', "Too Many Requests" is not valid JSON

### ISSUE THREAD

**Issue by sofakng** [t0bst4r/home-assistant-matter-hub#177]
I've just installed this using Docker and I'm accessing this through a reverse proxy (Traefik) but it shows an at the bottom:

"Unexpected token 'T', "Too Many Requests" is not valid JSON"

![image](https://github.com/user-attachments/assets/fd92a93d-7252-4f67-98e0-f4798fa96e2d)

Also, the [+] is missing to add a bridge ...

**Comment by t0bst4r** [comment]
The [+] is missing because the initial request to fetch the bridges already fails.

Can you open the "developer tools" of your browser (most browsers use F12).
Then switch to the network tab and refresh the page. There should be request failing (red) called "bridges".
Select it and head over to the "response" tab. What does it show?

**Comment by sofakng** [comment]
It's quite strange because if I refresh a couple of times it might work and then stop working.

I'm seeing lots of code 429 (Too Many Requests)...

Maybe something to do with the reverse proxy?  (I have the reverse proxy working with 10+ other applications so it's odd this isn't working by default)

**Comment by t0bst4r** [comment]
Interesting. I need to check if there is an error-handling bug. E.g. when it fails it retries immediately. And then you somehow get the too many requests error.

I'll try to reproduce it.

**Comment by t0bst4r** [comment]
After improving some things related to proxy / ingress, can you please try again as described here:

https://github.com/t0bst4r/home-assistant-matter-hub/blob/main/packages/documentation/faq/Running%20behind%20Reverse%20Proxy.md

**Comment by t0bst4r** [comment]
Since the app is running in host mode, the port is still externally reachable.

For security reasons you can limit the http port to an IP whitelist (e.g. only include the reverse proxy ip / 127.0.0.1).
The app logs (debug) the IP address which accesses the page. You can use this log to find the correct ip to whitelist for the reverse proxy.

See the configuration section in the readme for more details on how to configure it.
