### ISSUE TITLE
[Bug] Matter hub not picking up certain entities (when unique_id is missing for entities)

### ISSUE THREAD

**Issue by willyzha** [t0bst4r/home-assistant-matter-hub#193]
Only one of the light entities from home assistant are discovered by the home-assistant-matter-hub. I tried both pattern and entity match but neither are able to pick up my fans and one of my lights.
![image](https://github.com/user-attachments/assets/03468b4d-e465-46e0-b12c-23048170dc1f)

These are 4 entities that I have in my home assistant setup. I saw there was some logic in packages/backend/src/matter/devices/light-device.ts that filters based on color modes, as far as I can tell my my light should have been picked up.
![image](https://github.com/user-attachments/assets/65f37447-ca23-471c-8e21-102aefb5b23c)
![image](https://github.com/user-attachments/assets/aa8b6837-a28d-41eb-8975-9fc47fe34b74)

**Comment by t0bst4r** [comment]
Do they have a unique id?
You can check it by opening the entity‘s settings (where you assign labels or change the entity_id). 

it will tell you you cannot change its settings because its missing an unique id. 
I am aware of this and will improve it, but as of now those cannot be included.

![IMG_4866](https://github.com/user-attachments/assets/c97a64b3-b0a3-48ad-b60b-d092a0b8695a)

**Comment by willyzha** [comment]
Ah yes you're right. All of the devices that were not discovered do not have a unique id since i configured them through the yaml.

Thanks you! Is there already an issue created for this so I can keep track on any developments?

**Comment by willyzha** [comment]
Works if I manually add a `unique_id` in the home assistant yaml config

**Comment by t0bst4r** [comment]
This should have been fixed with the latest version. Can you please validate?
