### ISSUE TITLE
[Bug] climate shows cooling control for heating only devices

### ISSUE THREAD

**Issue by librehat** [t0bst4r/home-assistant-matter-hub#196]
As the title suggests, my thermostat is heating-only but it shows up in the bridge as if it can do both heating and cooling.

I'm not sure that Matter specification would enforce both to be present as there are vendors that provide matter connectivity in their new thermostats (e.g. Tado X), and this would've been very confusing to their customers.

**Comment by librehat** [comment]
Actually I found a usability bug, in order for me to change the temperature setting, I have to adjust both heating and cooling temperatures to the same position, otherwise it doesn't work (will be reverted back in a few seconds)

**Comment by KipK** [comment]
Can you show your thermostat entity from dev tools / states ?

**Comment by digiolin** [comment]
> Can you show your thermostat entity from dev tools / states ?

Hope this works 
```
hvac_modes:
  - "off"
  - auto
  - heat
min_temp: 4
max_temp: 35
target_temp_step: 0.5
current_temperature: 20.2
temperature: 35
hvac_action: heating
friendly_name: trv_1
supported_features: 385
```

**Comment by t0bst4r** [comment]
This is primarily caused by "auto" mode. 
i am mapping this to the "auto" mode in matter, which requires both cooling and heating. 
This is because the definition of auto is not the same. 

This is obviously wrong as I did it at the moment, but the consequence would be to not support auto mode for now.

I’ll need to dig into matter and ha definitions and see what we can do.
