### ISSUE TITLE
scene cannot be triggered via Google Home

### ISSUE THREAD

**Issue by Dr4g0nM4st3r** [t0bst4r/home-assistant-matter-hub#199]
If I release automations or scripts via the Matter hub (label: matter), they appear in Google Home as a new socket / device. These devices have the switching status “Off” and can be set to the status “On”, in which case the respective action is also executed. Unfortunately, this is different for scenes, which are displayed with the status “On” in Google Home. Unfortunately, I cannot switch these devices in this way, even if I first switch to Off and then back to On, no action is executed in HomeAssistant.

**Comment by yonm13** [comment]
I have the same issue. The weird thing is that they DID work in previous releases (I think around v.26).

**Comment by t0bst4r** [comment]
That is interesting… because I didn’t really change anything related since then. Except the major refactoring of the whole app all the time 😆 
But those shouldn’t have affected that.

Anyway can you please 
1. share the state (HA -> dev tools -> state -> search your scene) of your scene which shows as "on" in google home
2. share the **debug** log which happens when you switch it off and on from google home. Please only include the logs which happen at the time switching it on and off. Otherwise there will be a lot of logs to search.

**Comment by Dr4g0nM4st3r** [comment]
The debug from home assistant. Debug log from matter hub follows tomorrow.

![Uploading Screenshot_20241127_223816_Home Assistant.jpg…]()

**Comment by t0bst4r** [comment]
I have inverted the scene state (= always off). 
WIth that it can always be turned on.
In general, scenes cannot be turned off - also in Home assistant.

One problem:
Some controllers (like Alexa) assume that the device is "on" after the "on" button was pressed.
Therefore I cannot turn on the scene again. This refreshes after ~5 minutes. After that the device is off again and can be turned on.
