### ISSUE TITLE
[Bug]: Long devices names are truncated

### ISSUE THREAD

**Issue by mwhrtin** [t0bst4r/home-assistant-matter-hub#267]
### Version

3.0.0-alpha.51

### Matter Controller

Google Home, Apple Home

### Steps to reproduce

I've created a couple of helper light groups in Home Assistant with longer names. These device names are truncated by the Matter hub, and I need to manually edit them (e.g., in the Apple Home app) to display the correct name.

<img width="932" alt="truncated_device_name" src="https://github.com/user-attachments/assets/08aa52c8-9d45-4736-8123-9dd2b1a4a635">

The correct name should be `Inomhusbelysning utan fönsterlampor`; instead, the device is given the name `Inomhusbelysning utan fönste0c87`. 

### State and attributes

```
min_color_temp_kelvin: 2000
max_color_temp_kelvin: 6666
min_mireds: 150
max_mireds: 500
effect_list:
  - blink
  - breathe
  - candle
  - channel_change
  - colorloop
  - finish_effect
  - fireplace
  - okay
  - stop_colorloop
  - stop_effect
  - stop_hue_effect
supported_color_modes:
  - color_temp
  - xy
effect: null
color_mode: color_temp
brightness: 90
color_temp_kelvin: 2260
color_temp: 442
hs_color:
  - 29.589
  - 81.993
rgb_color:
  - 255
  - 149
  - 46
xy_color:
  - 0.572
  - 0.389
entity_id:
  - light.belysning_vaning_1_utan_fonsterlampor
  - light.belysning_vaning_2_utan_fonsterlampor
icon: mdi:lightbulb-group
friendly_name: Inomhusbelysning utan fönsterlampor
supported_features: 44
hide_attributes:
  - templates
  - icon_color
```

### Documentation & Issues

- [X] I have reviewed the [documentation](https://github.com/t0bst4r/home-assistant-matter-hub/blob/main/packages/documentation/README.md) and the linked troubleshooting guide.
- [X] I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar problem.

**Comment by Moonbase59** [comment]
I wasn't sure if there is a character limit in Matter, so I didn't complain, but I see the same here, which makes Google Nest devices speak odd (shortened) names, like "Schlafzimmer Nachttischl" for "Schlafzimmer Nachttischlampe" and other longer names. Unfortunately, German (like some other languages) has rather long names, if one sticks to a scheme…

Using HA 2024.12.0 and HAMH 3.0.0-alpha.51.

**Comment by t0bst4r** [comment]
Yes, this field is limited to 32 characters. 

Some controllers like Alexa don’t show the (entity) id anywhere. For the user the name is the only way to identify a device in the Alexa app. Often entities have similar names when they are part of a single device in HA. So when all of them are cut by 32 chars the user cannot tell them apart.

That’s why I decided to cut it and replaced the last 4 characters with a hash of the name. This is making the name unique.

**Comment by nicoh88** [comment]
@t0bst4r 

Hi, thanks for the info.

Would it then perhaps be possible to define an alternative alias in the device overview of the Matter hub, with which name the Matter hub transfers the device to Alexa?

I know that you can customize the device names in the Alexa app. However, we have several people in the household account and I would have to do this 2 or 3 times for each person who is to control the devices. Ultra annoying that Amazon hasn't managed this for years. If I didn't create the devices in the other profile, I would constantly hear from Alexa: “_The device cannot be controlled via your account, please change the account!_”

I can't change the device names for the entire HA so that I can control them properly by voice in Alexa - but get problems in HA.

Would be a cool feature!

![image](https://github.com/user-attachments/assets/dd9b5e02-c6ab-4468-8923-bd42bc1b8de0)
