### ISSUE TITLE
I can't install the add one

### ISSUE THREAD

**Issue by smolka186** [t0bst4r/home-assistant-matter-hub#292]
Hello
I can't install the add one
![image](https://github.com/user-attachments/assets/5368af83-176b-4fc3-a59a-4552ad6dfdf3)

Every time come this pop-up

**Comment by Spider6662k** [comment]
Same here

![image](https://github.com/user-attachments/assets/da30a311-372e-4bb5-8384-3b913aefc506)

**Comment by satho2210** [comment]
![image](https://github.com/user-attachments/assets/64bbb1dd-86b2-46fc-9fae-236ca930e7f8)
I have the same issue

**Comment by satho2210** [comment]
### **UPDATE (Resolved for me):**
**The issue was caused by an incorrect DNS server IP configuration in Home Assistant.
To resolve it, go to Settings → System → Network, and check the DNS server settings. If it's incorrect, update & save it accordingly. After that, reinstall the add-on, and it should work.
I believe this issue was related to a misconfiguration in my setup and is not related to the add-on itself.**

**Comment by Spider6662k** [comment]
@satho2210 thx, know it works

**Comment by t0bst4r** [comment]
Yes, this definitely looks like a connectivity issue. The installation process couldn’t fetch the app from npm.
