### ISSUE TITLE
[Bug]: Long Entity Names Truncated Incorrectly and Propagated to Alexa

### ISSUE THREAD

**Issue by ohrenmasken** [t0bst4r/home-assistant-matter-hub#315]
### Version

3.0.0-alpha.55

### Matter Controller

Alexa

### Steps to reproduce

When an entity has a long name, it is truncated incorrectly, and the truncated name is also reflected in Alexa. For example, an entity named "This is a very long name for a device" is shortened to "This is a very long name fordba4". This truncated name is then displayed in Alexa, which can cause confusion. The issue affects the usability and clarity of entity names in smart home integrations.

Steps to Reproduce:
Create an entity with a long name, e.g., "This is a very long name for a device".
Check the entity’s name as displayed in the Home Assistant interface.
Integrate the entity with Alexa and observe the truncated name there (or also in the add-on overview)

Expected Behavior:
The full name of the entity should be supported and displayed consistently across all platforms, including Alexa, without truncation.

Actual Behavior:
The name is truncated (e.g., "This is a very long name fordba4") and reflected in the Alexa integration.

<img width="1453" alt="Bildschirmfoto 2024-12-16 um 11 01 31" src="https://github.com/user-attachments/assets/2fb3ea4a-05e6-4f0b-ac5f-329d68ea9363" />

### Documentation & Issues

- [X] I have reviewed the [documentation](https://github.com/t0bst4r/home-assistant-matter-hub/blob/main/packages/documentation/README.md) and the linked troubleshooting guide.
- [X] I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar problem.

**Comment by t0bst4r** [comment]
Matter limits the name to 32 characters max.
There is not a thing we could do about it.
Only option is to truncate the name.

But since many HA Integrations name their entities similar it can be even more confusing when you see 5 devices with the same truncated name because the difference is after 32 chars. That’s why I decided to add the short hash at the end (last 4 chars) if the name is truncated. That’s the only way to identify devices with identical truncated names. In those cases I recommend renaming the device in Alexa itself
